name: 🚀 Auto Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🧰 Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install dependencies
        run: npm install

      - name: 🏗️ Build project
        run: npm run build

      - name: 🚀 Upload to Hostinger via FTP
        uses: samkirkland/ftp-deploy-action@v4.3.4
        with:
          server: ftp://157.173.208.175
          username: u288920822
          password: Bk@31012004
          local-dir: ./dist
